/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = 'dfkxffdplikdyhuvubnr';
export const publicAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRma3hmZmRwbGlrZHlodXZ1Ym5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMjI5NTksImV4cCI6MjA4NjU5ODk1OX0.cTJoF4JC2j7qw8QGt2JNcXupIQEDvdwbCUOfm-fGOAI';
